### PR TITLE
reusable classes added to main css

### PR DESCRIPTION
**Pull request by carlitos-0411**
Sir i have seen other reusable classes too but pls see i have added them correcltly or not and this is my first issue so if its not correctly done pls guide me how to do it

### CODE REVIEW

**Review by Safnaj — COMMENTED** [review]
This is just few, we have lot more classes for headings and other styles

**Comment by carlitos-0411** [comment]
> This is just few, we have lot more classes for headings and other styles

**Comment by carlitos-0411** [comment]
yes sir there are a lot more but i want to know that i have added this class correctly or not as i am not sure about it so first i added only one reusable class

**Review by Shehanka — CHANGES_REQUESTED** [review]
@carlitos-0411 You have added css classes to wrong css file. 
What we expecting is refactor Angular components common css classes into styles.css file

**Pull request closed without merging**
