### PR TITLE
Fixed-issue#90

### PR DESCRIPTION
**Pull request by pasxn**

### CODE REVIEW

**Comment by ebonynon** [comment]
@pasxn good job. Please provide screenshots n add issue to description
LGTM

**Review by Safnaj — COMMENTED** [review]
Good job..! Can u please share a screenshot ?

**Comment by pasxn** [comment]
Of the interface?

**Comment by SahasR** [comment]
@pasxn Yep, take a snipping tool and take a screenshot of UI in mobile view

**Comment by pasxn** [comment]
Screenshot from 2021-01-11 09-44-29

**Comment by Safnaj** [comment]
@pasxn Nicely done. If you can add a bit margin to right side it will look neat. 
and if you click the toggle, is the menus in right place ?

**Review by Shehanka — APPROVED** [review]

**Comment by Shehanka** [comment]
Accidentally closed the PR. now I cannot reopen it 🥶

**Comment by Safnaj** [comment]
I think it should be done by the sender

**Comment by Safnaj** [comment]
@pasxn Can you re open this pull request ?

**Comment by pasxn** [comment]
How?

**Comment by Safnaj** [comment]
@pasxn If you dont see a Reopen pull request here, can you please open a new one ?

**Pull request closed without merging**
