### PR TITLE
Contact Us Page Structure Created

### PR DESCRIPTION
**Pull request by SahasR**
The FrontEnd for the Contact Us Page has been created with three text boxes and one submit button.
Notice: There is not backend to this Contact Us page and it doesnt handle any submits

### CODE REVIEW

**Review by Shehanka — APPROVED** [review]
Code looks good to me

**Comment by SahasR** [comment]
Capture

Picture of the current UI

**Comment by Shehanka** [comment]
@SahasR add our SM icons with links

**Comment by SahasR** [comment]
Capture
Final look of UI

**Review by Shehanka — APPROVED** [review]

**Pull request merged**
