### PR TITLE
Fixed form validation

### LINKED ISSUE #349: Contact Form Button with Pointer
Button should show pointer on hover

Fix :
`cursor: pointer;`

### LINKED ISSUE #350: Contact Form Validation

### PR DESCRIPTION
**Pull request by Akalanka47000**
Fixes #350 
Fixes #349

### CODE REVIEW

**Review by Safnaj — APPROVED** [review]

**Comment by Safnaj** [comment]
@Akalanka47000 seems #349 not fixed yet

**Comment by Akalanka47000** [comment]
I'll have another look tomorrow, last I checked it was showing the pointer cursor on hover once I removed the disabled attribute. Just to be on the same page we're both talking about the send button below the contact form right?

**Comment by Akalanka47000** [comment]
I checked and it seems that the pointer looks okay. However there were a few other issues I noticed and fixed alongside this

**Comment by Akalanka47000** [comment]
Added a cache control header, lemme know if the issue still persists

**Pull request merged**
