### PR TITLE
Added mascot to homepage

### LINKED ISSUE #312: Add Mascot to Home Page
Akalanka Assign some one to this.

### PR DESCRIPTION
**Pull request by Akalanka47000**
Screenshot_1
Fixes #312

### CODE REVIEW

**Comment by Bawanthathilan** [comment]
Looks like it doesn't fit @Shehanka  :(

**Comment by Shehanka** [comment]
> Looks like it doesn't fit @Shehanka :(

Ack!

**Comment by Shehanka** [comment]
@Akalanka47000 refer this https://wif-web.web.app

**Comment by Akalanka47000** [comment]
Screenshot_2
Will this be okay?

**Review by Bawanthathilan — APPROVED** [review]

**Pull request merged**
