### PR TITLE
add some styling about us page service and history section

### PR DESCRIPTION
**Pull request by Bawanthathilan**

### CODE REVIEW

**Review by Safnaj — COMMENTED** [review]
Good One..! Thanks

**Comment by Safnaj** [comment]
@Bawanthathilan provide a screen shot pls

**Comment by Bawanthathilan** [comment]
> 
> 
> @Bawanthathilan provide a screen shot pls

image

**Comment by Safnaj** [comment]
- [ ] In the what we do sections, instead of those circles we can add some icons.
- [ ] Increase the line height and font spacing for FOSS History contents
- [ ] Have to Include Vision & Mission same as mentioned in this [Site](https://victorthemes.com/themes/caspiar/about-us/)

**Comment by Bawanthathilan** [comment]
> 
> 
>     * [x]  In the what we do sections, instead of those circles we can add some icons.
> 
>     * [x]  Increase the line height and font spacing for FOSS History contents
> 
>     * [x]  Have to Include Vision & Mission same as mentioned in this [Site](https://victorthemes.com/themes/caspiar/about-us/)
> 
> 
> @Sewvandiii will share the contents

@Sewvandiii please added contents

**Comment by Shehanka** [comment]
@Safnaj are we good to merge this?

**Comment by Safnaj** [comment]
Right contents need to be added.

**Comment by Sewvandiii** [comment]
**Our Vision✍** 

Support and inspire the global community on behalf of Free and Open Source Applications throughout the path to reach the optimum standard of technology!

**Our Mission✍** 

Educating and promoting groups and amplifying and advocating the message of the FOSS ideology to achieve software independence for all SLIIT FOSS enthusiasts.

**Our Strategy✍** 

Support FOSS related projects and communities in Sri Lanka in infrastructure and advisory

**Comment by Bawanthathilan** [comment]
> 
> 
> Right contents need to be added.

@Safnaj 
image

**Review by Shehanka — APPROVED** [review]
Good job

**Pull request merged**
