### PR TITLE
changed a webp file of logo

### LINKED ISSUE #372: Add Purple BG Logo and set as per the theme.
The Logo Should also with the Purple BG.

Screenshot 2022-10-22 at 12 49 23 AM

### PR DESCRIPTION
**Pull request by darshitdudhaiya**
[https://github.com/sliit-foss/sliitfoss/issues/372](url)

### CODE REVIEW

**Review by Akalanka47000 — CHANGES_REQUESTED** [review]
Hello, 

First off, thanks for the contribution on behalf of the SLIIT FOSS community.
Sadly however both themes seem to break with this fix

- Dark mode - Missing transparency in the logo background
- Dark mode - Background purple and navbar purple are two different color codes
- Light mode - Background should be the original dark gray color

image

image

image

image

**Comment by darshitdudhaiya** [comment]
Ok I will keep that changes and i will done it in few hours. I want to do
this so you can assign it to me?

**Comment by Akalanka47000** [comment]
Sure😄

**Comment by darshitdudhaiya** [comment]
@Akalanka47000 Do you want your logo to be different in dark and light mode? because in this website navbar color and body color are totally different so pls clarify it.

**Comment by Akalanka47000** [comment]
> @Akalanka47000 Do you want your logo to be different in dark and light mode? because in this website navbar color and body color are totally different so pls clarify it.

Sorry for the late reply, in the dark mode the logo background should be the same color as the background color of the navbar and in the light mode it should be the same dark gray color as it was in the original logo

**Comment by Akalanka47000** [comment]
Further there seems to be an outline which has been left during the background removal process😟
image

**Comment by Akalanka47000** [comment]
I've updated the format of the .env file as well required for running the project without which you might be stuck. The file is at the root of the project name .env.test. Apologies for the inconvenience.

**Pull request closed without merging**
