### PR TITLE
Site NavBar & Footer Added

### PR DESCRIPTION
**Pull request by Safnaj**
Following changes has been made to the repo..

- Bootstrap Added
- Site Structure Created
- Routing Module Implemented
- Footer, NavBar Components added

### CODE REVIEW

**Comment by Shehanka** [comment]
@Safnaj can u add screenshots?

**Review by Shehanka — APPROVED** [review]
Code looks good to me

**Comment by Safnaj** [comment]
> @Safnaj can u add screenshots?

**Comment by Safnaj** [comment]
> @Safnaj can u add screenshots?

Screenshot 2020-10-08 at 6 26 35 PM

**Comment by Shehanka** [comment]
> > @Safnaj can u add screenshots?
> 
> Screenshot 2020-10-08 at 6 26 35 PM

what's this?

**Comment by Safnaj** [comment]
> @Safnaj can u add screenshots?

Screenshot 2020-10-09 at 6 57 52 PM

**Pull request merged**
