### PR TITLE
Events Carousel Added

### PR DESCRIPTION
**Pull request by Safnaj**
I have added owl-carousel slider for past events. But it have some  following issues.

- Navigation dots not showing
- auto slide not working
- slide work with mouse drag.

@Shehanka can u have a look by refer ur website carousel ??

### CODE REVIEW

**Comment by Shehanka** [comment]
> I have added owl-carousel slider for past events. But it have some following issues.
> 
> * Navigation dots not showing
> * auto slide not working
> * slide work with mouse drag.
> 
> @Shehanka can u have a look by refer ur website carousel ??

I got the same issue with my website. I guess something wrong with the owl carousl.

**Review by Shehanka — APPROVED** [review]

**Comment by Safnaj** [comment]
> > I have added owl-carousel slider for past events. But it have some following issues.
> > 
> > * Navigation dots not showing
> > * auto slide not working
> > * slide work with mouse drag.
> > 
> > @Shehanka can u have a look by refer ur website carousel ??
> 
> I got the same issue with my website. I guess something wrong with the owl carousl.

I checked ur site. u have only the responsive issue in the carousel. Here its not auto sliding too. 
check the code. I have searched a lot and solutions were same

**Comment by Shehanka** [comment]
> > > I have added owl-carousel slider for past events. But it have some following issues.
> > > 
> > > * Navigation dots not showing
> > > * auto slide not working
> > > * slide work with mouse drag.
> > > 
> > > @Shehanka can u have a look by refer ur website carousel ??
> > 
> > 
> > I got the same issue with my website. I guess something wrong with the owl carousl.
> 
> I checked ur site. u have only the responsive issue in the carousel. Here its not auto sliding too.
> check the code. I have searched a lot and solutions were same

Did you fix the responsive issue here?

**Comment by Safnaj** [comment]
> > > > I have added owl-carousel slider for past events. But it have some following issues.
> > > > 
> > > > * Navigation dots not showing
> > > > * auto slide not working
> > > > * slide work with mouse drag.
> > > > 
> > > > @Shehanka can u have a look by refer ur website carousel ??
> > > 
> > > 
> > > I got the same issue with my website. I guess something wrong with the owl carousl.
> > 
> > 
> > I checked ur site. u have only the responsive issue in the carousel. Here its not auto sliding too.
> > check the code. I have searched a lot and solutions were same
> 
> Did you fix the responsive issue here?

Not yet. but can be fixed once its worked.
Compare ur carousel code and this one and let me know.

**Pull request merged**
