### PR TITLE
Feature/we do

### PR DESCRIPTION
**Pull request by ebonynon**
There is an issue with grid

Screenshot_2020-10-14 SLIIT FOSS(1)

### CODE REVIEW

**Comment by Safnaj** [comment]
is this happened with primer or bootstrap ?

**Comment by ebonynon** [comment]
> is this happened with primer or bootstrap ?

I tried both of them but I couldn't do it; bootstrap grid and primer grid are very same.

**Review by Shehanka — CHANGES_REQUESTED** [review]
Code looks good to me. @Bawanthathilan can you help him to resolve this styling error

**Review by KaveeshaG — CHANGES_REQUESTED** [review]
Styles are not in standered accordiing to the Design standerd, Hows the Nav bar will get bit hight and logo align bit to thr right and make the Nav links to the middle with good letter spacing and add the search.

**Comment by ebonynon** [comment]
> Styles are not in standered accordiing to the Design standerd

😟

> Hows the Nav bar will get bit hight and logo align bit to thr right and make the Nav links to the middle with good letter spacing and add the search.

image

[](https://postimg.cc/CRkdqKMZ)

There is a big difference between wireframe and actual desing so we must reimplement navbar with svg (honestly current navbar is temporary one)

**Comment by Shehanka** [comment]
> Styles are not in standered accordiing to the Design standerd, Hows the Nav bar will get bit hight and logo align bit to thr right and make the Nav links to the middle with good letter spacing and add the search.

I guess, @ebonynon is lacking styling so @KaveeshaG can you guide him

**Comment by KaveeshaG** [comment]
> 
> 
> > Styles are not in standard according to the Design standard, Hows the Navbar will get bit hight and logo align bit to the right and make the Nav links to the middle with good letter spacing and add the search.
> 
> I guess, @ebonynon is lacking styling so @KaveeshaG can you guide him
>
> Nice, I hope it's good to notify earlier whether the current frontend implementation and next frontend implementation like "this is a temporary one".

**Comment by Shehanka** [comment]
@ebonynon you haven't declared height for components that's why they're overlapping

**Comment by Shehanka** [comment]
Screenshot 2020-10-20 at 00 27 22

**Pull request merged**
